server:
  port: 8080
spring:
  application:
    name: config-reader-client
  config:
    import: optional:configserver:http://localhost:8888
  profiles:
    active: dev

management:
  endpoints:
    web:
      exposure:
        include: '*'

logging:
  level:
    org.springframework.cloud.config.client: DEBUG
    org.springframework.boot.context.config: DEBUG
